logging:
  logLevel: 0
  logIntoConsole: true
  logIntoFile: true
  logPath: '${WORKSPACE}/logs'
global:
  workspace: '/Volumes/School/LSP-reforged/LSP-Reforged'
  defaultLanguage: 'zh_cn'
auth:
  __client_id: ''
  _uid: ''
  authString: 'LSPaintBoard'
  registerBeforeS: 1145141919810
  tokenCooldownMs: 300000
localization:
  zh_cn: '${WORKSPACE}/lang/zh_cn.json'
database:
  path: '${WORKSPACE}/db.db'