logging:
  logLevel: 1
  logIntoConsole: true
  logIntoFile: true
  logPath: ${WORKSPACE}/logs
global:
  workspace: /paintboard/LSP-Reforged
  defaultLanguage: zh_cn
  port: 40001
  wsPort: 40002
  wsUseTLS: false
  certPath: ''
  keyPath: ''
auth:
  __client_id: ''
  _uid: ''
  authString: LSPaintBoard-2025
  registerBeforeS: 1735660800
  tokenCooldownMs: 30000
localization:
  zh_cn: ${WORKSPACE}/lang/zh_cn.json
database:
  path: ${WORKSPACE}/db_new.db
paintboard:
  height: 600
  width: 1000
  activityStartTimestamp: 0
  activityEndTimestamp: 1738252800
  cooldown: 1
  resetBoard: false
