logging:
  logLevel: 1
  logIntoConsole: true
  logIntoFile: true
  logPath: ${WORKSPACE}/logs
global:
  workspace: /paintboard/LSP-Reforged
  defaultLanguage: zh_cn
  port: 40001
  wsPort: 40002
  wsUseTLS: true
  certPath: /etc/letsencrypt/live/paintboard.ayakacraft.com/fullchain.pem
  keyPath: /etc/letsencrypt/live/paintboard.ayakacraft.com/privkey.pem
auth:
  __client_id: 1cc234266111f10d67289a16d1eb571664e1f855
  _uid: '378849'
  authString: LSPaintBoard
  registerBeforeS: 1735660800
  tokenCooldownMs: 30000
localization:
  zh_cn: ${WORKSPACE}/lang/zh_cn.json
database:
  path: ${WORKSPACE}/db.db
paintboard:
  height: 600
  width: 1000
  activityStartTimestamp: 1737993600
  activityEndTimestamp: 1738252800
  cooldown: 30000
  resetBoard: true
