logging:
  logLevel: 1
  logIntoConsole: true
  logIntoFile: true
  logPath: ${WORKSPACE}/logs
global:
  workspace: /Volumes/School/LSP-reforged/LSP-Reforged
  defaultLanguage: zh_cn
  port: 25566
  wsPort: 25567
  certPath: ''
  keyPath: ''
auth:
  __client_id: ''
  _uid: ''
  authString: LSPaintBoard
  registerBeforeS: 1145141919810
  tokenCooldownMs: 30000
localization:
  zh_cn: ${WORKSPACE}/lang/zh_cn.json
database:
  path: ${WORKSPACE}/db.db
paintboard:
  height: 600
  width: 1000
  activityStartTimestamp: 0
  activityEndTimestamp: 1145141919810
  cooldown: -1
  resetBoard: true
